### ISSUE TITLE
大佬，请问是怎么找到getMultiReserveTime这个请求的？

### ISSUE THREAD

**Issue by xiaosaxd** [6r6/maicai.ddxq.tools#1]
我抓包里面并没有看到这个接口，直接调用的时候返回“您的访问已过期,请重新登录app~”。加上cookie之后，返回“参数错误”。

**Comment by xiaosaxd** [comment]
或者请问一下这个接口的参数是怎么样的，谢谢大佬~

**Comment by 6r6** [comment]
Hi @xiaosaxd 可以试试抓包微信电脑版的买菜小程序，比较简单。

**Comment by xiaosaxd** [comment]
好的已经搞定过了。
app里面抓不到，小程序里面可以~谢谢大佬~
