### ISSUE TITLE
jq报错”jq: error (at <stdin>:0): Cannot index array with string "time"“

### ISSUE THREAD

**Issue by wongzeon** [6r6/maicai.ddxq.tools#4]
有这个报错，是正常运行还是不正常呢？感觉不太对

**Comment by hogannnn** [comment]
> 
因为curl二选一了，所以
 try parse as getMultiReserveTime或parse as getReserveTime下面对应代码注释掉就行了。

**Comment by wongzeon** [comment]
> > 
> 
> 因为curl二选一了，所以 try parse as getMultiReserveTime或parse as getReserveTime下面对应代码注释掉就行了。

嗯，刚解决，谢谢！
